### ISSUE TITLE
Details to add

### ISSUE THREAD

**Issue by mosabua** [WiredEnterprise/Lord-of-the-Files#32]
You might want to add that there are plenty of other formats beyond txt available that are ascii based and better suitable for writing. E.g. we use asciidoc to create books and slides and collaborate on github for them. 

E.g. https://github.com/sonatype/nexus-book

has a full publishing pipeline including CI build and push to server including pdf and html generation.

The Hudson Book I wrote is similar and also produces epub.. 

https://github.com/hudson/hudson-book

Just an idea ;-)

**Comment by WiredEnterprise** [comment]
Thanks for suggesting that. Do you have that same needle-in-a-haystack problem with asciidoc? One big issue was that we'd get long paragraphs with undocumented changes and would have to scan through them for often very minor changes.

**Comment by mosabua** [comment]
In my experience this is not too bad with asciidoc. You have to try to break up paragraphs a bit more if it gets crazy... the main thing I noticed however is that it will differ depending on the the diff viewer you use. Some seem to be able to better display the difference the others. E.g. the built in one in IntelliJ IDEA is excellent and beats eg. the github webview and gitk in most cases..
